app.name: cln-spend-and-replace-plugin (dev)
app.description: A spring boot bitcoin demo application

spring.application.name: ${app.name}
spring.http.log-request-details: true

server.port: 8080
server.use-forward-headers: true
server.compression.enabled: true

management.server.port: 9001

# LOGGING
# logging.file.path: ./var/log
logging.file.name: ${logging.file.path}/cln-spend-and-replace-plugin-dev.log
#logging.config: classpath:logback-development.xml
logging.level.org.springframework: INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
logging.level.web: DEBUG

org.tbk.xchange:
  specifications:
    krakenExchange:
      exchange-class: org.knowm.xchange.kraken.KrakenExchange
      exchange-specific-parameters:
        Use_Sandbox: true