app.name: cln-spend-and-replace-plugin
app.description: A spring boot bitcoin demo application

spring.application.name: ${app.name}
spring.http.log-request-details: false

server.port: 8080
server.use-forward-headers: true
server.compression.enabled: true

management.server.port: 9001

# LOGGING
logging.file.path: ${HOME}
logging.file.name: ${logging.file.path}/cln-spend-and-replace-plugin.log
# Note: logback.xml comes from jrpclightning library!
logging.config: classpath:logback.xml
logging.logback.rollingpolicy.clean-history-on-start: true
logging.level.org.springframework: INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
#logging.level.web: DEBUG

org.tbk.cln.plugin.spend-and-replace:
  enabled: true
  dry: true  # keep in 'demo mode' till reaching v0.0.1

org.tbk.xchange:
  enabled: true
  specifications:
    pluginExchange:
      exchange-class: org.knowm.xchange.kraken.KrakenExchange
      should-load-remote-meta-data: false
      #api-key: 'your-dev-api-key'
      #secret-key: 'your-dev-secret-key'
