app.name: cln-spend-and-replace-plugin (test)
app.description: A spring boot bitcoin demo application

spring.application.name: ${app.name}
spring.http.log-request-details: false

server.port: 8080
server.use-forward-headers: true
server.compression.enabled: true

management.server.port: 9001

org.tbk.xchange:
  enabled: true
  specifications:
    pluginExchange:
      exchange-class: org.tbk.cln.sar.test.DummyExchange
      #exchange-class: org.knowm.xchange.kraken.KrakenExchange
